
var __cov_$8RfTlszZIcjLgY_0uqUMA = (Function('return this'))();
if (!__cov_$8RfTlszZIcjLgY_0uqUMA.__coverage__) { __cov_$8RfTlszZIcjLgY_0uqUMA.__coverage__ = {}; }
__cov_$8RfTlszZIcjLgY_0uqUMA = __cov_$8RfTlszZIcjLgY_0uqUMA.__coverage__;
if (!(__cov_$8RfTlszZIcjLgY_0uqUMA['/Users/mani/work/coverage-istanbul-wdio/test/web.js'])) {
   __cov_$8RfTlszZIcjLgY_0uqUMA['/Users/mani/work/coverage-istanbul-wdio/test/web.js'] = {"path":"/Users/mani/work/coverage-istanbul-wdio/test/web.js","s":{"1":1,"2":0,"3":0,"4":0},"b":{"1":[0,0],"2":[0,0]},"f":{"1":0},"fnMap":{"1":{"name":"myClickFunc","line":1,"loc":{"start":{"line":1,"column":0},"end":{"line":1,"column":22}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":3,"column":1}},"2":{"start":{"line":2,"column":4},"end":{"line":2,"column":27}},"3":{"start":{"line":5,"column":0},"end":{"line":5,"column":41}},"4":{"start":{"line":7,"column":0},"end":{"line":7,"column":133}}},"branchMap":{"1":{"line":7,"type":"cond-expr","locations":[{"start":{"line":7,"column":29},"end":{"line":7,"column":47}},{"start":{"line":7,"column":50},"end":{"line":7,"column":63}}]},"2":{"line":7,"type":"cond-expr","locations":[{"start":{"line":7,"column":92},"end":{"line":7,"column":99}},{"start":{"line":7,"column":102},"end":{"line":7,"column":111}}]}},"code":["(function () { function myClickFunc(){","    console.log('link   ');","}","","var el = document.getElementById('link');","","el[window.addEventListener ? 'addEventListener' : 'attachEvent']( window.addEventListener ? 'click' : 'onclick', myClickFunc, false);","","}());"]};
}
__cov_$8RfTlszZIcjLgY_0uqUMA = __cov_$8RfTlszZIcjLgY_0uqUMA['/Users/mani/work/coverage-istanbul-wdio/test/web.js'];
function myClickFunc(){__cov_$8RfTlszZIcjLgY_0uqUMA.f['1']++;__cov_$8RfTlszZIcjLgY_0uqUMA.s['2']++;console.log('link   ');}__cov_$8RfTlszZIcjLgY_0uqUMA.s['3']++;var el=document.getElementById('link');__cov_$8RfTlszZIcjLgY_0uqUMA.s['4']++;el[window.addEventListener?(__cov_$8RfTlszZIcjLgY_0uqUMA.b['1'][0]++,'addEventListener'):(__cov_$8RfTlszZIcjLgY_0uqUMA.b['1'][1]++,'attachEvent')](window.addEventListener?(__cov_$8RfTlszZIcjLgY_0uqUMA.b['2'][0]++,'click'):(__cov_$8RfTlszZIcjLgY_0uqUMA.b['2'][1]++,'onclick'),myClickFunc,false);
